"""Train YOLOv8n on cable-damage, synthetic home wires, or real circuit faults. GPU auto-detected."""
from __future__ import annotations

import argparse
import json
import shutil
from datetime import datetime, timezone
from pathlib import Path

import yaml
from ultralytics import YOLO

from src.datautil import class_names, count_split_images, resolve_yaml, rewrite_paths
from src.device import resolve_device, train_runtime
from src.trainer import DefectTrainer, small_object_hyps

ROOT = Path(__file__).resolve().parents[1]

PRESETS = {
    "cable_damage": {
        "data": ROOT / "data" / "public" / "cable-damage",
        "local_yaml": "cable-damage.local.yaml",
        "run_name": "cable_damage_n",
        "weights": ROOT / "models" / "investor_proof.pt",
        "proof": ROOT / "results" / "investor_proof",
        "claim": "Public RGB cable-damage detection is trainable. This is not a home-panel thermal model.",
        "dataset_name": "Roboflow 100 cable-damage",
        "source": "https://huggingface.co/datasets/LibreYOLO/cable-damage",
        "license": "CC BY 4.0",
        "modality": "RGB (not thermal)",
        "need": "python -m src.download_cable_damage",
    },
    "home_wires": {
        "data": ROOT / "data" / "public" / "home-wires",
        "local_yaml": "home-wires.local.yaml",
        "run_name": "home_wires_n",
        "weights": ROOT / "models" / "home_wires.pt",
        "proof": ROOT / "results" / "home_wires",
        "claim": "YOLO can locate red/blue (and IEC/legacy) home-circuit conductors. Synthetic bootstrap — mix real board photos next.",
        "dataset_name": "home-wires (synthetic IEC/legacy conductors)",
        "source": "generated by python -m src.build_home_wires",
        "license": "in-repo bootstrap (not a public photo corpus)",
        "modality": "RGB synthetic home wiring (not thermal, not in-wall)",
        "need": "python -m src.build_home_wires",
    },
    "circuit_faults": {
        "data": ROOT / "data" / "public" / "circuit-faults",
        "local_yaml": "circuit-faults.local.yaml",
        "run_name": "circuit_faults_n",
        "weights": ROOT / "models" / "circuit_faults.pt",
        "proof": ROOT / "results" / "circuit_faults",
        "claim": "YOLO can locate complete vs open vs short vs damage on real circuit/cable photos. PCB traces ≠ home T&E.",
        "dataset_name": "circuit-faults (PKU-Market-PCB + DeepPCB + RF100 cable-damage)",
        "source": "https://huggingface.co/datasets/RobotHuman/PCB_defect + thangkt/PCB-Prune-YOLO-DeepPCB + LibreYOLO/cable-damage",
        "license": "research-use PCB sets + cable-damage CC BY 4.0",
        "modality": "RGB photographs of PCBs and cables (not thermal, not residential DBs)",
        "need": "python -m src.download_circuit_faults",
    },
    "home_faults": {
        "data": ROOT / "data" / "public" / "home-faults",
        "local_yaml": "home-faults.local.yaml",
        "run_name": "home_faults_n",
        "weights": ROOT / "models" / "home_faults.pt",
        "proof": ROOT / "results" / "home_faults",
        "claim": "Defect-only YOLO (open/short/damage) on PCB AOI + cables + stripped-wire close-ups. Still not a Pakistani consumer-unit model. No complete class.",
        "dataset_name": "home-faults (circuit-faults minus complete + PCB-IND + stripped-wire)",
        "source": "PKU + DeepPCB + RF100 cable-damage + Zenodo PCB-IND + Zenodo stripped-wire",
        "license": "mixed research/CC BY 4.0 public sets",
        "modality": "RGB photos of PCBs, outdoor cables, and insulated-wire close-ups (not thermal, not Pakistani DBs)",
        "need": "python -m src.download_home_data && python -m src.build_home_faults",
    },
}


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train tiny YOLO (cable damage, home wires, or circuit faults).")
    p.add_argument("--preset", choices=sorted(PRESETS), default="cable_damage")
    p.add_argument("--data", type=Path, default=None, help="Override dataset folder (must contain data.yaml)")
    p.add_argument("--model", default="yolov8n.pt")
    p.add_argument("--epochs", type=int, default=15)
    p.add_argument("--imgsz", type=int, default=None, help="Default 320 on CPU, 640 on GPU")
    p.add_argument("--batch", type=int, default=None, help="Default 8 on CPU, 16 on GPU")
    p.add_argument("--workers", type=int, default=None)
    p.add_argument("--device", default="auto", help="auto | cpu | 0 | 0,1")
    p.add_argument("--name", default=None)
    p.add_argument("--no-enhance-aug", action="store_true", help="Disable CLAHE/sharpen train-time extra and small-object hyps")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    preset = PRESETS[args.preset]
    dataset_dir = args.data or preset["data"]
    device = resolve_device(args.device)
    rt = train_runtime(device, args.batch, args.imgsz, args.workers)
    run_name = args.name or preset["run_name"]

    try:
        yaml_src = resolve_yaml(dataset_dir)
    except FileNotFoundError:
        raise SystemExit(f"No data.yaml in {dataset_dir}. Run: {preset['need']}")
    data_yaml = rewrite_paths(yaml_src, preset["local_yaml"])
    print("preset", args.preset)
    print("Using", data_yaml)
    print("device", rt["device"], "imgsz", rt["imgsz"], "batch", rt["batch"], "amp", rt["amp"])

    extra = {}
    trainer_cls = None
    if args.preset == "home_wires":
        # Insulation color is the class. Default Ultralytics HSV would scramble red vs brown vs blue.
        extra = {"hsv_h": 0.01, "hsv_s": 0.2, "hsv_v": 0.3}
    elif args.preset in {"circuit_faults", "home_faults"}:
        extra = {"hsv_h": 0.015, "hsv_s": 0.25, "hsv_v": 0.35}
        if not args.no_enhance_aug:
            extra.update(small_object_hyps())
            trainer_cls = DefectTrainer

    model_path = args.model
    if args.preset == "home_faults" and args.model == "yolov8n.pt":
        prior = ROOT / "models" / "circuit_faults.pt"
        if prior.exists():
            model_path = str(prior)
            print("fine-tune from", model_path)
    model = YOLO(model_path)
    train_kw = dict(
        data=str(data_yaml),
        epochs=args.epochs,
        imgsz=rt["imgsz"],
        batch=rt["batch"],
        device=rt["device"],
        workers=rt["workers"],
        project=str(ROOT / "runs"),
        name=run_name,
        exist_ok=True,
        patience=6,
        plots=True,
        pretrained=True,
        verbose=True,
        amp=rt["amp"],
        **extra,
    )
    if trainer_cls is not None:
        train_kw["trainer"] = trainer_cls
    model.train(**train_kw)
    run_dir = ROOT / "runs" / run_name
    best = run_dir / "weights" / "best.pt"
    if not best.exists():
        raise SystemExit(f"Training finished but {best} is missing")

    cfg = yaml.safe_load(data_yaml.read_text(encoding="utf-8"))
    split = "test" if cfg.get("test") else "val"
    best_model = YOLO(str(best))
    metrics = best_model.val(
        data=str(data_yaml),
        imgsz=rt["imgsz"],
        batch=rt["batch"],
        device=rt["device"],
        workers=rt["workers"],
        split=split,
        plots=True,
    )
    map50 = float(metrics.box.map50)
    map5095 = float(metrics.box.map)
    precision = float(metrics.box.mp)
    recall = float(metrics.box.mr)
    print("mAP50", map50, "mAP50-95", map5095, "P", precision, "R", recall)

    names = class_names(cfg)
    per_class = {}
    maps = getattr(metrics.box, "maps", None)
    if maps is not None:
        for i, name in enumerate(names):
            if i < len(maps):
                per_class[name] = round(float(maps[i]), 4)

    weights_out: Path = preset["weights"]
    proof_dir: Path = preset["proof"]
    weights_out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(best, weights_out)
    proof_dir.mkdir(parents=True, exist_ok=True)
    for fname in (
        "results.png",
        "confusion_matrix.png",
        "BoxPR_curve.png",
        "PR_curve.png",
        "F1_curve.png",
        "val_batch0_pred.jpg",
    ):
        src = run_dir / fname
        if src.exists():
            shutil.copy2(src, proof_dir / fname)

    payload = {
        "created_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "claim": preset["claim"],
        "dataset": {
            "name": preset["dataset_name"],
            "source": preset["source"],
            "license": preset["license"],
            "classes": names,
            "splits": count_split_images(dataset_dir),
            "modality": preset["modality"],
        },
        "training": {
            "architecture": "YOLOv8n",
            "imgsz": rt["imgsz"],
            "epochs": args.epochs,
            "batch": rt["batch"],
            "device": rt["device"],
            "amp": rt["amp"],
            "weights": str(weights_out.relative_to(ROOT)).replace("\\", "/"),
            "small_object_hyps": bool(trainer_cls),
            "enhance_train_aug": bool(trainer_cls),
        },
        "test_metrics": {
            "split": split,
            "mAP50": round(map50, 4),
            "mAP50-95": round(map5095, 4),
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "per_class_mAP50-95": per_class,
        },
        "not_claimed": [
            "Detection of in-wall / hidden wiring faults",
            "Radiometric thermal Delta-T on residential boards",
            "A board is electrically safe",
            "Paper mAP figures (Tao 98.7%, Chen 99%) as this model's score",
            "Synthetic home-wires mAP as field accuracy on real consumer units",
            "PCB open/short mAP as accuracy on residential T&E or Pakistani DBs",
        ],
    }
    metrics_path = proof_dir / "metrics.json"
    metrics_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    print("Wrote", metrics_path)
    print("Copied weights to", weights_out)


if __name__ == "__main__":
    main()
